config/routes.rb
Rails.application.routes.draw do
  resources :user_files
  resources :user_files
  resources :folders
  devise_for :users

  root 'dashboard#index'
  get  'files', to: 'user_files#new',    as: :root_upload_file
  post 'files', to: 'user_files#create', as: :post_root_upload_file
  get  'files/*path', to: 'user_files#new',    as: :upload_file
  post 'files/*path', to: 'user_files#create', as: :post_upload_file

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  has_many :files, class_name: "UserFile"
  validates :path, presence: true, allow_blank: true
  validates :path, uniqueness: true
  alias_attribute :name, :path

  def title
    "/#{path.presence}"
  end

  def root?
    path.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_file.rb
require "digest"
# What we should do:
# identify files and make snapshot of it as kde does it (async)
# async download for:
#  * magnet
#  * web
# states to started and ready files
# after file done and checksum changed, save binary diff
class UserFile < ActiveRecord::Base
  WORKER_LIST = [HttpJob]
  attr_accessor :temp_file, :file_last_action
  belongs_to :folder
  belongs_to :user

  validates_presence_of   :folder_id#, :user_id
  validates_presence_of   :checksum, :extension, :file, unless: :pending?
  validates_uniqueness_of :file_name, scope: :folder_id

  after_validation :localize_file
  after_save :run_processor


  state_machine :initial => :local do
    state :pending    # state when need to fetch
    state :local      # on local machine
    state :processing # on image resized/preview on video
    state :completed  # all prepared
    state :uploaded   # is on the cloud

    event :local do
      transition :to => :local
    end

    event :process do
      transition :to => :processing
    end

    event :complete do
      transition [:local, :processing, :completed] => :completed
    end

    event :upload do
      transition [:completed, :uploaded] => :uploaded
    end
  end

  def dir
    Rails.root.join("public/system/user_files/#{folder.path}")
  end

  def path
    dir.join(file_name)
  end

  # accepts binary file
  def file= val
    self.state     = :local
    self.file_name = val.original_filename
    self.extension = File.extname(file_name)[1..-1]
    self.checksum  = Digest::SHA2.hexdigest(val.tempfile.read)
    @temp_file = val
    @file_last_action = __method__.to_sym
  end
  def file; @temp_file; end

  # takes file from the string
  # if protocols are http ftp then curl/wget
  # if magnet then set to torrent
  # both are async
  def file_url= val
    return if val.blank?

    self.state       = :pending
    self.server_data = val
    @file_last_action = __method__.to_sym
  end
  def file_url; end

  private
  def localize_file
    return if errors.any? || @temp_file.nil?

    FileUtils.mkdir_p(dir)
    FileUtils.copy_file(@temp_file.path, path)
  end


  # some other job should decide what to do
  # in order to better support if errors occured
  def run_processor
    if @file_last_action == :file_url
      processor = WORKER_LIST.detect{|worker| worker.can_work_with_file_name?(val) }
      processor.perform_later(self)
    elsif @file_last_action == :file

    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  def create
    @folder = Folder.new(path: [params[:path], folder_params[:name]].select(&:present?).join("/"))

    if @folder.save
      redirect_to upload_file_path(path: @folder.path), notice: 'Folder was successfully created.'
    else
      @folder.path = folder_params[:path]
      render :new
    end
  end

  # PATCH/PUT /folders/1
  def update
    if @folder.update(folder_params)
      redirect_to upload_file_path(path: @folder.path), notice: 'Folder was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /folders/1
  def destroy
    @folder.destroy
    redirect_to root_path, notice: 'Folder was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find_or_initialize_by(id: params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def folder_params
      params.require(:folder).permit(:name, :path)
    end
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  before_action :set_folder
  before_action :set_user_file, only: [:show, :edit, :update, :destroy]


  # GET /user_files/1
  def show
  end

  # GET /user_files/new
  def new
    @user_file = @folder.files.new
  end

  # GET /user_files/1/edit
  def edit
  end

  # POST /user_files
  def create
    Folder.transaction do
      @folder.save!
      (Array(params[:user_file][:file]).each do |file|
        @folder.files.create!(file: file)
      end
      params[:user_file][:file_url].to_s.split("\n")).each do |link|
        @folder.files.create!(file_url: link)
      end
    end
    redirect_to folder_path, notice: 'User file was successfully created.'
  rescue ActiveRecord::RecordInvalid
    new
    render :new
  end

  # PATCH/PUT /user_files/1
  def update
    if @user_file.update(user_file_params)
      redirect_to @user_file, notice: 'User file was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_files/1
  def destroy
    @user_file.destroy
    redirect_to user_files_url, notice: 'User file was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_file
      @user_file = @folder.files.find(params[:id])
    end

    def set_folder
      @folder = Folder.find_or_initialize_by(path: params[:path].to_s)
      @folder.save! if @folder.root? # need always create it
    end

    # Only allow a trusted parameter "white list" through.
    def user_file_params
      params.require(:user_file).permit(:file, :file_url)
    end

    def folder_path
      params[:path].nil? ? root_upload_file_path : upload_file_path(params[:path])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/dashboard/index.html.erb
<%= link_to 'New Folder', new_folder_path %>
<%= link_to 'Files', root_upload_file_path %>

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= text_field_tag(:path, params[:path]) if params[:path].present?%>/<%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/_menu.html.haml
= render 'user_files/menu'

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %>
</p>

<p>
  <strong>Lft:</strong>
  <%= @folder.lft %>
</p>

<p>
  <strong>Rgt:</strong>
  <%= @folder.rgt %>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/user_files/_form.html.haml
= form_for @user_file, url: request.path do |f|
  - if @user_file.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_file.errors.count, "error")} prohibited this user_file from being saved:"
      %ul
        - @user_file.errors.full_messages.each do |msg|
          %li= msg

  .field
    folder:
    = @folder.title
  .field
    = f.label :file
    = f.file_field :file, multiple: true
    %br
    = f.text_area :file_url, placeholder: 'or paste here link'
  .actions
    = f.submit 'Save'

app/views/user_files/_list.html.haml
%h1 Listing user_files

%table
  %thead
    %tr
      %th Folder
      %th Extension
      %th File name
      %th
      %th
      %th

  %tbody
    - @folder.files.each do |user_file|
      - next unless user_file.persisted?
      %tr
        %td= user_file.folder.title
        %td= user_file.extension
        %td= user_file.file_name
        %td= link_to 'Show', user_file
        %td= link_to 'Edit', edit_user_file_path(user_file)
        %td= link_to 'Destroy', user_file, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/user_files/_menu.html.haml
= link_to "Root", root_upload_file_path, class: 'pure-menu-heading'
%ul.pure-menu-list
  - Folder.order(:name).each do |f|
    %li.pure-menu-item{class: params[:path].eql?(f.name.presence) && 'pure-menu-selected'}
      = link_to f.title, (f.root? ? root_upload_file_path : upload_file_path(path: f.name)), class: 'pure-menu-link'
  -#%li.pure-menu-item
    %a.pure-menu-link{:href => "/tools/"} Tools
  %li.pure-menu-item.menu-item-divided
    = link_to "Add folder", new_folder_path(path: params[:path]), class: "pure-menu-link"
  %li.pure-menu-item
    %a.pure-menu-link{:href => "javascript:void(0);"} Upload here

app/views/user_files/edit.html.haml
%h1 Editing user_file

= render 'form'

= link_to 'Show', @user_file
\|
= link_to 'Back', user_files_path

app/views/user_files/new.html.haml
= render 'list'

%h1 New user_file
= render 'form'

= link_to 'Back', user_files_path

app/views/user_files/show.html.haml
%p#notice= notice

%p
  %b Folder:
  = @user_file.folder
%p
  %b User:
  = @user_file.user
%p
  %b Changes:
  = @user_file.changes
%p
  %b Checksum:
  = @user_file.checksum
%p
  %b Extension:
  = @user_file.extension
%p
  %b File uid:
  = @user_file.file_uid
%p
  %b File name:
  = @user_file.file_name

= link_to 'Edit', edit_user_file_path(@user_file)
\|
= link_to 'Back', user_files_path